// ==UserScript==
// @name         suno: bigger multiselect buttons, selection range by shift click
// @version      2026.03.06.0422
// @description  shift click selects all between selection and clicked item, so click on first, then shift click on last, you can also deselect
// @author       hg42
// @namespace    http://github.com/hg42/suno-userscripts
// @icon         https://www.google.com/s2/favicons?sz=64&domain=suno.com
// @match        https://suno.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // --- CONFIGURABLE VARIABLES ---

    // --- GLOBAL STATE ---
    let lastClickedButton = null;
    let lastClickedIndex = -1;
    let allSelectableItems = []; // Cache of all relevant multi-select buttons

    const style = document.createElement('style');
    style.textContent = `
       .clip-row {
         display: flex;
         align-items: stretch;
       }
       .clip-row > div {
         height: 100%;
         display: flex;
         align-items: stretch;
       }
       .clip-row .multi-select-button {
         flex-grow: 1;
         height: 100% !important;
         display: flex;
         align-items: center;
         justify-content: center;
         padding: 0 !important;
         margin: 0 !important;
         background-color: transparent !important;
         border: none !important;
       }
       off----------.clip-row .multi-select-button .not-hover-only {
         display: none !important;
       }
       .clip-row .multi-select-button button {
         width: 100% !important;
         height: 100% !important;
         border-radius: 0 !important;
         padding: 0 !important;
         background-color: transparent !important;
         border: none !important;
         opacity: 1 !important;
       }
       .clip-row .multi-select-button button span {
         width: 100%;
         height: 100%;
         display: flex;
         align-items: center;
         justify-content: center;
       }
       .clip-row .multi-select-button button svg {
         width: 24px !important;
         height: 24px !important;
         opacity: 0.5;
       }
       .clip-row .multi-select-button button:hover {
         background-color: rgba(255, 255, 255, 0.1) !important;
       }
    `;
    document.head.appendChild(style);

    // --- FUNCTIONS ---

    // Function to determine if a multi-select button is currently selected
    // Selected means the '.hover-only' class is ABSENT.
    function isButtonSelected(buttonElement) {
        return !buttonElement.classList.contains('hover-only');
    }

    // Function to set the selection state of a multi-select button
    // 'select' = true means selected (remove .hover-only), false means unselected (add .hover-only)
    function setButtonSelectionState(buttonElement, select) {
        if (select) {
            buttonElement.classList.remove('hover-only');
        } else {
            buttonElement.classList.add('hover-only');
        }
    }

    // Function to simulate a native click event on a button.
    // This is used to trigger the site's own JavaScript handlers for selection.
    // A custom property 'isSynthetic' is added to allow our own event listener
    // to distinguish between user-generated and script-generated clicks.
    function simulateNativeClick(buttonElement) {
        const clickEvent = new MouseEvent('click', {
            view: unsafeWindow, // Use unsafeWindow for the view property
            bubbles: true,
            cancelable: true,
            // Custom property to mark this as a synthetic event
            isSynthetic: true
        });
        buttonElement.dispatchEvent(clickEvent);
    }

    // Function to update the cached list of multi-select buttons and attach listeners
    function updateButtonsAndListeners() {
        allSelectableItems = []; // Clear the cache
        const multiSelectButtons = document.querySelectorAll('.clip-row .multi-select-button button');

        multiSelectButtons.forEach(button => {
            // Ensure the button is not already handled to prevent duplicate listeners
            if (!button.dataset.listenerAttached) {
                button.addEventListener('click', handleMultiSelectClick);
                button.dataset.listenerAttached = 'true'; // Mark as handled
            }
            // Store the button directly
            allSelectableItems.push(button);
        });
    }

    // Event handler for multi-select button clicks
    function handleMultiSelectClick(event) {
        // Check if this click was generated by our script (e.g., during a shift-click range selection).
        // If it is, we want it to trigger the native site handlers, but not re-enter our shift-click logic.
        const isSynthetic = event.isSynthetic === true;

        const clickedButton = event.currentTarget;
        const currentIndex = allSelectableItems.findIndex(item => item === clickedButton);

        if (currentIndex === -1) {
            console.warn('Clicked button not found in allSelectableItems cache.');
            // If a button is clicked but not in our cache, it might be a newly added element
            // that hasn't been picked up by the observer yet. We can still update lastClicked
            // if it's a real user click, but it won't participate in shift-click range.
            if (!isSynthetic) {
                lastClickedButton = clickedButton;
                lastClickedIndex = currentIndex; // -1 indicates not in cache
            }
            return;
        }

        // Handle Shift-Click for range selection
        if (event.shiftKey && lastClickedButton && lastClickedIndex !== -1 && currentIndex !== -1 && !isSynthetic) {
            event.preventDefault(); // Prevent the default action for the *current* button click

            const start = Math.min(lastClickedIndex, currentIndex);
            const end = Math.max(lastClickedIndex, currentIndex);

            // Determine the target state: what the clickedButton *would* be after a normal click.
            // Since we prevented default, the clickedButton's state hasn't changed yet.
            const targetSelectedState = !isButtonSelected(clickedButton);

            // Apply the target state to all buttons in the range
            for (let i = start; i <= end; i++) {
                const buttonToModify = allSelectableItems[i];
                if (buttonToModify && isButtonSelected(buttonToModify) !== targetSelectedState) {
                    // Manually change the visual state (add/remove .hover-only class)
                    setButtonSelectionState(buttonToModify, targetSelectedState);
                    // Simulate a native click to trigger the site's internal logic for this button.
                    // This simulated click will have `isSynthetic: true` and will be ignored by
                    // our shift-click logic, but will still update `lastClickedButton/Index` below.
                    simulateNativeClick(buttonToModify);
                }
            }
            // After a shift-click, the last clicked item becomes the current one for future shift-clicks
            lastClickedButton = clickedButton;
            lastClickedIndex = currentIndex;

        } else if (!isSynthetic) { // This is a normal user click (not synthetic, not shift-click)
            // Mimic the original code's behavior: prevent default, manually toggle, then simulate click.
            // This ensures our script has full control over the state change and then consistently
            // triggers the site's logic, regardless of the button's native behavior.
            event.preventDefault();

            // Toggle the state manually
            const newState = !isButtonSelected(clickedButton);
            setButtonSelectionState(clickedButton, newState);

            // Simulate a native click to trigger the site's internal logic
            simulateNativeClick(clickedButton);

            lastClickedButton = clickedButton;
            lastClickedIndex = currentIndex;
        } else { // This is a synthetic click (isSynthetic is true)
            // For synthetic clicks, we just update the last clicked info.
            // We don't want to re-process shift-click logic or prevent default.
            lastClickedButton = clickedButton;
            lastClickedIndex = currentIndex;
        }
    }

    // --- INITIALIZATION AND OBSERVATION ---

    // Use MutationObserver to detect when new .clip-row elements are added to the DOM
    const observer = new MutationObserver(mutations => {
        let needsUpdate = false;
        for (const mutation of mutations) {
            if (mutation.addedNodes.length > 0) {
                for (const node of mutation.addedNodes) {
                    // Check if the added node itself is a .clip-row or contains one
                    if (node.nodeType === 1 && (node.matches('.clip-row') || node.querySelector('.clip-row'))) {
                        needsUpdate = true;
                        break;
                    }
                }
            }
            if (needsUpdate) break;
        }
        if (needsUpdate) {
            updateButtonsAndListeners();
        }
    });

    // Start observing the document body for child list changes and subtree modifications
    observer.observe(document.body, { childList: true, subtree: true });

    // Initial setup for elements already present on page load
    updateButtonsAndListeners();

})();
